version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/map_my_world

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: map_my_world
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"